# File realm in ES format (from the CLI or manually assembled)
kind: Secret
apiVersion: v1
metadata:
  name: es-filerealm-secret
  namespace: logging
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kube-system"
stringData:
  users: Jyc=
  users_roles: Jyc=
